set_property IOSTANDARD LVCMOS33 [get_ports LEDenable0]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property PACKAGE_PIN A16 [get_ports LEDenable0]
set_property PACKAGE_PIN B15 [get_ports SCL0]
set_property PACKAGE_PIN B16 [get_ports SDA0]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN V17 [get_ports enable]
set_property PACKAGE_PIN U18 [get_ports measureBTN_d]
set_property PACKAGE_PIN W17 [get_ports measureSW]
set_property PACKAGE_PIN W15 [get_ports nrst]
set_property PACKAGE_PIN V16 [get_ports {gain[1]}]
set_property PACKAGE_PIN W16 [get_ports {gain[0]}]
set_property PACKAGE_PIN L1 [get_ports {red[15]}]
set_property PACKAGE_PIN P1 [get_ports {red[14]}]
set_property PACKAGE_PIN N3 [get_ports {red[13]}]
set_property PACKAGE_PIN P3 [get_ports {red[12]}]
set_property PACKAGE_PIN U3 [get_ports {red[11]}]
set_property PACKAGE_PIN W3 [get_ports {red[10]}]
set_property PACKAGE_PIN V3 [get_ports {red[9]}]
set_property PACKAGE_PIN V13 [get_ports {red[8]}]
set_property PACKAGE_PIN V14 [get_ports {red[7]}]
set_property PACKAGE_PIN U14 [get_ports {red[6]}]
set_property PACKAGE_PIN U15 [get_ports {red[5]}]
set_property PACKAGE_PIN W18 [get_ports {red[4]}]
set_property PACKAGE_PIN V19 [get_ports {red[3]}]
set_property PACKAGE_PIN U19 [get_ports {red[2]}]
set_property PACKAGE_PIN E19 [get_ports {red[1]}]
set_property PACKAGE_PIN U16 [get_ports {red[0]}]
set_property PACKAGE_PIN W19 [get_ports ready0]
set_property IOSTANDARD LVCMOS33 [get_ports SCL0]
set_property IOSTANDARD LVCMOS33 [get_ports SDA0]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports measureBTN_d]
set_property IOSTANDARD LVCMOS33 [get_ports measureSW]
set_property IOSTANDARD LVCMOS33 [get_ports nrst]
set_property IOSTANDARD LVCMOS33 [get_ports ready0]
set_property IOSTANDARD LVCMOS33 [get_ports {gain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gain[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {red[0]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gain_IBUF[0]} {gain_IBUF[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {red_OBUF[0]} {red_OBUF[1]} {red_OBUF[2]} {red_OBUF[3]} {red_OBUF[4]} {red_OBUF[5]} {red_OBUF[6]} {red_OBUF[7]} {red_OBUF[8]} {red_OBUF[9]} {red_OBUF[10]} {red_OBUF[11]} {red_OBUF[12]} {red_OBUF[13]} {red_OBUF[14]} {red_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list measureBTN_d_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list measureSW_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list SDA0_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
